### ISSUE TITLE
Synchronous Context mode

### ISSUE THREAD

**Issue by knolleary** [flowforge/flowforge-nr-persistent-context#17]
### Description

The persistent context provided by these nodes is currently Async only due to the fact they read/write over the network.

Whilst Node-RED has long-supported async-only context stores, the reality is many users aren't aware of them and don't necessarily write code that can handle them.

We also may hit issues with node authors haven't done the right thing to support async-only stores.

Issue #16 is a good example - a bug in a *core* Node-RED node with async-only stores (mea culpa...).

The upshot of all this is a user's flows may not Just Work when importing into FlowForge.

We should add a synchronous mode for our context store. In summary that means having a local in-memory cache that the store can access synchronously, whilst persistent updates are made asynchronously. This is the model used by the Node-RED File-base context store when in synchronous mode.

To achieve that, when Node-RED starts up, the nodes will have to retrieve the full contents of context from the remote store. We apply a 10Mb storage limit on context, so this shouldn't be too much overhead to achieve.

We can reuse a lot of the same logic used in the file store around local caching and batching up writes over the network.

The File Store Service will need a new api adding to allow the bulk download of context.

**Comment by Steve-Mcl** [comment]
Re-opening as there is one more PR

**Comment by Steve-Mcl** [comment]
TODO...

- [ ] update readme (change "Currently, only async versions of context get and context set are supported e.g")

**Comment by Steve-Mcl** [comment]
Tested on staging


![Image](https://user-images.githubusercontent.com/44235289/218704042-dec17c0f-114f-44b6-aed1-68cddf0960d2.gif)

```
[{"id":"a4350eab0e5f4873","type":"inject","z":"33fa381a21b22be0","name":"inject direct from context","props":[{"p":"payload.flow","v":"#:(persistent)::test","vt":"flow"},{"p":"payload.global","v":"#:(persistent)::test","vt":"global"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","x":850,"y":160,"wires":[["3eb83f2da9260b35"]]},{"id":"f07371a971629061","type":"debug","z":"33fa381a21b22be0","name":"debug 8","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"{\t     \"flow\": $flowContext('test', 'persistent'),\t     \"global\": $globalContext('test', 'persistent')\t}\t\t\t","targetType":"jsonata","statusVal":"payload","statusType":"auto","x":1080,"y":100,"wires":[]},{"id":"644d7722cefd20fa","type":"inject","z":"33fa381a21b22be0","name":"","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{}","payloadType":"json","x":790,"y":60,"wires":[["8edaa68c07e852d6"]]},{"id":"8edaa68c07e852d6","type":"change","z":"33fa381a21b22be0","name":"put random 1~10 in flow.test & global.test","rules":[{"t":"set","p":"#:(persistent)::test","pt":"global","to":"(\t    $minimum := 1;\t    $maximum := 10;\t    $round(($random() * ($maximum-$minimum)) + $minimum, 0)\t)","tot":"jsonata"},{"t":"set","p":"#:(persistent)::test","pt":"flow","to":"(\t   $minimum := 1;\t   $maximum := 10;\t   $round(\t       ($random() * ($maximum-$minimum)) + $minimum,\t       0\t   ) \t)","tot":"jsonata"}],"action":"","property":"","from":"","to":"","reg":false,"x":1040,"y":60,"wires":[["f07371a971629061"]]},{"id":"3eb83f2da9260b35","type":"debug","z":"33fa381a21b22be0","name":"debug 9","active":true,"tosidebar":true,"console":false,"tostatus":true,"complete":"payload","targetType":"msg","statusVal":"payload","statusType":"auto","x":1080,"y":160,"wires":[]}]
```

**Comment by Steve-Mcl** [comment]
Additional note: 
Persistent values set in synchronous mode were still present after the project was restarted
